use mysql;
use training21;

-- LIST ALL MANAGER DATA
select * from emp where job='MANAGER';

-- LIST EMP WHO ARE WORKING AS MANAGER OR ANALYST OR CLERK
select * from emp where job='MANAGER' or job='ANALYST' or job='CLERK';
select * from emp where job in ('CLERK','MANAGER','ANALYST');

-- LIST EMP WHO ARE EARNING SAL BETWEEN 3000 AND 5000(INCLUSIVE OF LIMIT)
SELECT * FROM EMP WHERE SAL BETWEEN 3000 AND 5000;

-- LIST EMP WHO ARE WORKING AS MANAGER OR ANALYST OR CLERK 
-- AND EARNING SAL BETWEEN 3000 AND 5000 
SELECT EMPNO,ENAME,JOB,SAL FROM EMP WHERE 
JOB IN ('CLERK','MANAGER','ANALYST') AND SAL BETWEEN 3000 AND 5000;

-- LIST ALL EMP WHO ARE EARNING COMM
select * from emp where comm>0;
SELECT EMPNO,ENAME,JOB,SAL FROM EMP WHERE COMM>0;

-- LIST ALL EMP WHOSE COMM IS NOT NULL
select * from emp where comm IS NOT NULL;

-- LIST ALL EMP WHOSE NAME STARTS WITH S
SELECT * FROM EMP WHERE ENAME LIKE 'S%';

-- LIST ALL EMP WHOSE NAME ENDS WITH R
SELECT * FROM EMP WHERE ENAME LIKE '%R';

-- LIST EMP WHOSE NAME CONTAINS A LETTER
SELECT * FROM EMP WHERE ENAME LIKE '%A%';

-- LIST EMP WHOSE NAME CONTAINS A AS SECOND LETTER
SELECT * FROM EMP WHERE ENAME LIKE '_A%';

-- LIST EMP WHOSE NAME STARTS WITH EITHER M OR S LETTER
SELECT * FROM EMP WHERE ENAME LIKE 'S%' OR ENAME LIKE 'M%';

-- LIST EMP WHOSE NAME STARTS BETWEEN A TO M
SELECT * FROM EMP WHERE ENAME REGEXP '^[A-M]';

-- LIST EMP WHOSE NAME CONTAINS _
SELECT * FROM EMP WHERE ENAME REGEXP '_';

-- LIST ALL EMP WHO ARE WORKING AS MANAGER IN EITHER DEPT 10 OR 20 
-- AND ALL CLERK FOR DEPT3 30
SELECT * FROM EMP WHERE JOB='MANAGER' AND DEPTNO IN ('10','20') OR JOB='CLERK' AND DEPTNO='30';

-- LIST ENAME, SAL AND BONUS AS 10% OF SALARY
SELECT ENAME,SAL,(SAL*10/100) AS BONUS FROM EMP;

-- LIST EMP DATA AS PER THE ASCENDING ORDER OF NAME
SELECT * FROM EMP ORDER BY ENAME;

-- 17.LIST ALL AS PER THEIR SALARY HIGHES TO LOWEST
SELECT * FROM EMP ORDER BY SAL DESC;

-- 18.LIST EMP AS PER THEIR DEPT, WITH IN DEPT HIGHEST TO LOWEST SAL
SELECT EMPNO,ENAME,DEPTNO,SAL FROM EMP
ORDER BY DEPTNO, SAL DESC;

-- 19.LIST TOP 3 HIGHEST PAID EMP
SELECT * FROM EMP ORDER BY SAL DESC LIMIT 3;

-- 20.RETURN SEQUENTIAL NUMBER RETURN RANK BASED ON SPECIFIED CRITERIA 
-- IF TWO EMP HAVE SAME SALARY THEY BOTH GET SAME NUMBER AND NEXT NUMBER WILL BE SKIPPED
SELECT EMPNO,ENAME,DEPTNO,SAL,
RANK() OVER(partition by DEPTNO ORDER BY SAL DESC) AS 'RANK' FROM EMP;

-- 21.RETURN CONSUCUTIVE RANKING VALUES BASED ON SPECIFIED CRITERIA
SELECT EMPNO,ENAME,DEPTNO,SAL,
DENSE_RANK() OVER(partition by DEPTNO ORDER BY SAL DESC) AS 'RANK' FROM EMP;

-- 22.LIST DIFFERENT JOB NAME
SELECT JOB FROM EMP GROUP BY JOB;

-- 23.LIST TOTAL ORGANIZATION SALARY
SELECT SUM(SAL) AS TOTAL_ORG_SAL FROM EMP;

-- 24.LIST DEPTWISE TOTAL SALARY
SELECT DEPTNO,SUM(SAL) AS TOTAL_DEPT_SAL FROM EMP GROUP BY DEPTNO;

-- 25.LIST JOBWISE EMP COUNT
SELECT JOB,COUNT(*) AS EMP_COUNT FROM EMP GROUP BY JOB;

-- 26.LIST ALL EMP WHO HAVE JOINED IN THE MONTH OF FEB
SELECT * FROM EMP WHERE MONTH(HIREDATE) = 2;

-- 27.LIST EMP COUNT JOINED BETWEEN 1981 AND 1983
SELECT COUNT(*) AS EMP_COUNT FROM EMP WHERE HIREDATE BETWEEN '1981-01-01' AND '1983-12-31';

-- 28.LIST HOW MANY YEARS OF SERVICE COMPLETED BY EACH EMP ARRAANGED BASED ON TENURE HIGHEST TO LOWEST
SELECT ENAME,YEAR(NOW())-YEAR(HIREDATE) AS 'TENURE' FROM EMP ORDER BY TENURE DESC;